// <auto-generated />
using System;
using LoanDeductionPrediction.Repositories.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoanDeductionPrediction.Repositories.Migrations
{
    [DbContext(typeof(LoanDeductionDbContext))]
    [Migration("20260831153151_AddBorrowerIdToLoanApplication")]
    partial class AddBorrowerIdToLoanApplication
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LoanDeductionPrediction.Repositories.Entities.BorrowerLoanApplication", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationId"));

                    b.Property<int>("BorrowerId")
                        .HasColumnType("int");

                    b.Property<string>("CollateralDetails")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("CollateralValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("InterestRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("LoanType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("MonthlySalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("RequestedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReviewedByLoanOfficerId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("TenureMonths")
                        .HasColumnType("int");

                    b.HasKey("ApplicationId");

                    b.HasIndex("BorrowerId");

                    b.HasIndex("Email");

                    b.HasIndex("ReviewedByLoanOfficerId");

                    b.HasIndex("Status");

                    b.ToTable("BorrowerLoanApplications", (string)null);
                });

            modelBuilder.Entity("LoanDeductionPrediction.Repositories.Entities.LoanAccount", b =>
                {
                    b.Property<int>("LoanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoanId"));

                    b.Property<int>("BorrowerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("Emiamount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("EMIAmount");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("LoanOfficerId")
                        .HasColumnType("int");

                    b.Property<decimal>("OutstandingAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrincipalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("TenureMonths")
                        .HasColumnType("int");

                    b.HasKey("LoanId");

                    b.HasIndex("BorrowerId");

                    b.HasIndex("LoanOfficerId");

                    b.ToTable("LoanAccounts", (string)null);
                });

            modelBuilder.Entity("LoanDeductionPrediction.Repositories.Entities.LoanHistory", b =>
                {
                    b.Property<int>("LoanHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoanHistoryId"));

                    b.Property<int>("BorrowerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EmiAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("InterestRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("LoanOfficerId")
                        .HasColumnType("int");

                    b.Property<int>("OriginalLoanId")
                        .HasColumnType("int");

                    b.Property<decimal>("OutstandingAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrincipalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TenureMonths")
                        .HasColumnType("int");

                    b.HasKey("LoanHistoryId");

                    b.HasIndex("OriginalLoanId");

                    b.ToTable("LoanHistories");
                });

            modelBuilder.Entity("LoanDeductionPrediction.Repositories.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BorrowerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("LoanId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("date");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.HasKey("PaymentId");

                    b.HasIndex("BorrowerId");

                    b.HasIndex("LoanId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("LoanDeductionPrediction.Repositories.Entities.PaymentBehaviorLog", b =>
                {
                    b.Property<int>("BehaviorLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BehaviorLogId"));

                    b.Property<int>("BorrowerId")
                        .HasColumnType("int");

                    b.Property<int>("DaysLate")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<int>("LoanId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("PaymentDate")
                        .HasColumnType("date");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.HasKey("BehaviorLogId");

                    b.HasIndex("BorrowerId");

                    b.HasIndex("LoanId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("PaymentBehaviorLogs", (string)null);
                });

            modelBuilder.Entity("LoanDeductionPrediction.Repositories.Entities.RefreshToken", b =>
                {
                    b.Property<int>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RefreshTokenId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RefreshTokenId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("LoanDeductionPrediction.Repositories.Entities.RepaymentSchedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<decimal>("Emiamount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("EMIAmount");

                    b.Property<int>("InstallmentNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("InterestAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LoanId")
                        .HasColumnType("int");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly?>("PaidDate")
                        .HasColumnType("date");

                    b.Property<decimal>("PrincipalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ScheduleId");

                    b.HasIndex("LoanId");

                    b.ToTable("RepaymentSchedules", (string)null);
                });

            modelBuilder.Entity("LoanDeductionPrediction.Repositories.Entities.RiskPrediction", b =>
                {
                    b.Property<int>("RiskPredictionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RiskPredictionId"));

                    b.Property<int>("BorrowerId")
                        .HasColumnType("int");

                    b.Property<int>("LoanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PredictionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("RiskScore")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("RiskPredictionId");

                    b.HasIndex("BorrowerId");

                    b.HasIndex("LoanId");

                    b.ToTable("RiskPredictions", (string)null);
                });

            modelBuilder.Entity("LoanDeductionPrediction.Repositories.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("UserId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("LoanDeductionPrediction.Repositories.Entities.BorrowerLoanApplication", b =>
                {
                    b.HasOne("LoanDeductionPrediction.Repositories.Entities.User", "Borrower")
                        .WithMany()
                        .HasForeignKey("BorrowerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LoanDeductionPrediction.Repositories.Entities.User", "ReviewedByLoanOfficer")
                        .WithMany("ReviewedBorrowerApplications")
                        .HasForeignKey("ReviewedByLoanOfficerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Borrower");

                    b.Navigation("ReviewedByLoanOfficer");
                });

            modelBuilder.Entity("LoanDeductionPrediction.Repositories.Entities.LoanAccount", b =>
                {
                    b.HasOne("LoanDeductionPrediction.Repositories.Entities.User", "Borrower")
                        .WithMany("LoanAccountBorrowers")
                        .HasForeignKey("BorrowerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LoanDeductionPrediction.Repositories.Entities.User", "LoanOfficer")
                        .WithMany("LoanAccountLoanOfficers")
                        .HasForeignKey("LoanOfficerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Borrower");

                    b.Navigation("LoanOfficer");
                });

            modelBuilder.Entity("LoanDeductionPrediction.Repositories.Entities.Payment", b =>
                {
                    b.HasOne("LoanDeductionPrediction.Repositories.Entities.User", "Borrower")
                        .WithMany()
                        .HasForeignKey("BorrowerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LoanDeductionPrediction.Repositories.Entities.LoanAccount", "Loan")
                        .WithMany()
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LoanDeductionPrediction.Repositories.Entities.RepaymentSchedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Borrower");

                    b.Navigation("Loan");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("LoanDeductionPrediction.Repositories.Entities.PaymentBehaviorLog", b =>
                {
                    b.HasOne("LoanDeductionPrediction.Repositories.Entities.User", "Borrower")
                        .WithMany("PaymentBehaviorLogs")
                        .HasForeignKey("BorrowerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LoanDeductionPrediction.Repositories.Entities.LoanAccount", "Loan")
                        .WithMany("PaymentBehaviorLogs")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LoanDeductionPrediction.Repositories.Entities.RepaymentSchedule", "Schedule")
                        .WithMany("PaymentBehaviorLogs")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Borrower");

                    b.Navigation("Loan");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("LoanDeductionPrediction.Repositories.Entities.RefreshToken", b =>
                {
                    b.HasOne("LoanDeductionPrediction.Repositories.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LoanDeductionPrediction.Repositories.Entities.RepaymentSchedule", b =>
                {
                    b.HasOne("LoanDeductionPrediction.Repositories.Entities.LoanAccount", "Loan")
                        .WithMany("RepaymentSchedules")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loan");
                });

            modelBuilder.Entity("LoanDeductionPrediction.Repositories.Entities.RiskPrediction", b =>
                {
                    b.HasOne("LoanDeductionPrediction.Repositories.Entities.User", "Borrower")
                        .WithMany("RiskPredictions")
                        .HasForeignKey("BorrowerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LoanDeductionPrediction.Repositories.Entities.LoanAccount", "Loan")
                        .WithMany("RiskPredictions")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Borrower");

                    b.Navigation("Loan");
                });

            modelBuilder.Entity("LoanDeductionPrediction.Repositories.Entities.LoanAccount", b =>
                {
                    b.Navigation("PaymentBehaviorLogs");

                    b.Navigation("RepaymentSchedules");

                    b.Navigation("RiskPredictions");
                });

            modelBuilder.Entity("LoanDeductionPrediction.Repositories.Entities.RepaymentSchedule", b =>
                {
                    b.Navigation("PaymentBehaviorLogs");
                });

            modelBuilder.Entity("LoanDeductionPrediction.Repositories.Entities.User", b =>
                {
                    b.Navigation("LoanAccountBorrowers");

                    b.Navigation("LoanAccountLoanOfficers");

                    b.Navigation("PaymentBehaviorLogs");

                    b.Navigation("RefreshTokens");

                    b.Navigation("ReviewedBorrowerApplications");

                    b.Navigation("RiskPredictions");
                });
#pragma warning restore 612, 618
        }
    }
}
